services:
  yolo:
    container_name: yolo_train
    build:
      context: .
    environment:
      # Authentification
      - BASIC_AUTH_USER=${BASIC_AUTH_USER}
      - BASIC_AUTH_PASS=${BASIC_AUTH_PASS}

      # Log level
      - LOG_LEVEL=INFO

      # Paths
      - PYTHONPATH=/app
      - MODEL_DIR=./models  # 用于标注的model
      - MODEL_FILENAME=best.pt
      - DATASET_DIR=/data/dataset
      - MODEL_PATH=./models/best.pt  # 没有默认使用yolov11

      # Train_config
      - TRAIN_EPOCHS=10
      - TRAIN_IMGSZ=640
      - TRAIN_BATCH_SIZE=16


#      - LABEL_STUDIO_URL=http://host.docker.internal:${PORT}
      - LABEL_STUDIO_URL=http://host.docker.internal:8080

      - TASK_TYPE=detection
      - LABEL_STUDIO_API_KEY=525b8630bc21a49ceb6d4b0d063edd22d66d932e
      - TASK_TYPE=detection

    ports:
      - "9090:9090"
    volumes:
      - "./data/server:/data"
      # 添加数据目录挂载，将Windows主机的数据目录挂载到容器内
      # - "{Your dataset path}:/data/dataset"
      - "F:/_Work/data_/haoyi/dataset:/data/dataset"

    develop:
      watch:
        - action: rebuild
          path: ./model.py
          target: /app/model.py
          